add annotations + podAnnotations
deckhouse/k8s-image-availability-exporter pull request #212
Opened 2024-07-22 11:52 UTC by beliys

PR for https://github.com/deckhouse/k8s-image-availability-exporter/issues/170
I also prefer to scrape via the `prometheus.io/scrape: 'true'` annotation

2024-07-22 12:01 UTC, beliys commented
@nabokihms

2024-08-03 14:36 UTC, nabokihms requested changes
Thanks, @0xbilko. This is a great improvement. Can you bump the chart version? (it is required to automatically release a new version on artifacthub)

2024-08-03 15:05 UTC, 0xbilko commented
@nabokihms, done

2024-08-05 16:34 UTC, nabokihms commented
Doc is not up to date. Could you execute the make docs as well?

2024-08-06 20:49 UTC, 0xbilko commented
@nabokihms, done

2024-08-20 06:16 UTC, nabokihms commented on charts/k8s-image-availability-exporter/Chart.yaml
> +appVersion: "0.10.0"
```suggestion
appVersion: "0.9.0"
```

2024-08-20 06:16 UTC, nabokihms commented on charts/k8s-image-availability-exporter/README.md
> +![Version: 0.15.0](https://img.shields.io/badge/Version-0.15.0-informational?style=flat-square) ![AppVersion: 0.10.0](https://img.shields.io/badge/AppVersion-0.10.0-informational?style=flat-square)
```suggestion
![Version: 0.15.0](https://img.shields.io/badge/Version-0.15.0-informational?style=flat-square) ![AppVersion: 0.9.0](https://img.shields.io/badge/AppVersion-0.9.0-informational?style=flat-square)
```

2024-08-20 06:20 UTC, merged

2024-08-20 06:21 UTC, nabokihms commented
@0xbilko thanks!